/**
 * @file dict_magic_codes.c
 * @brief MAGIC Status Code String Helper Functions
 * @description 提供状态码到字符串的转换函数（用于日志和调试）
 *
 * 注意：本文件只处理 MAGIC-Status-Code AVP (10053)。
 *      对于 Result-Code AVP (268)，请使用 freeDiameter 内置的错误处理函数。
 */

#include "dict_magic_codes.h"
#include <stddef.h>
#include <stdint.h>

/**
 * @brief 将 MAGIC-Status-Code (AVP 10053) 转换为可读字符串。
 * @details 内部使用 switch-case 匹配所有已定义的 MAGIC
 * 状态宏，用于生成人类可读的日志。
 *
 * @param code MAGIC 状态码 (1000-3001)。
 * @return const char* 状态码描述字符串，未知码返回 "UNKNOWN_MAGIC_STATUS"。
 *
 * @note 此函数仅用于 MAGIC-Status-Code AVP，受 `dict_magic_codes.h` 定义保护。
 *       对于 Result-Code AVP (268)，使用 freeDiameter 的标准函数。
 * @warning 此函数返回的是指向静态字符串常量的指针，不应被释放。
 */
const char *magic_status_code_str(uint32_t code) {
  switch (code) {
  /* MAGIC 参数错误 (1000-1037) */
  case MAGIC_ERROR_MISSING_AVP:
    return "MAGIC_ERROR_MISSING_AVP";
  case MAGIC_ERROR_AUTHENTICATION_FAILED:
    return "MAGIC_ERROR_AUTHENTICATION_FAILED";
  case MAGIC_ERROR_UNKNOWN_SESSION:
    return "MAGIC_ERROR_UNKNOWN_SESSION";
  case MAGIC_ERROR_MAGIC_NOT_RUNNING:
    return "MAGIC_ERROR_MAGIC_NOT_RUNNING";
  case MAGIC_ERROR_ENUMERATION_OUT_OF_RANGE:
    return "MAGIC_ERROR_ENUMERATION_OUT_OF_RANGE";
  case MAGIC_ERROR_MALFORMED_LINK_STRING:
    return "MAGIC_ERROR_MALFORMED_LINK_STRING";
  case MAGIC_ERROR_MALFORMED_QOS_STRING:
    return "MAGIC_ERROR_MALFORMED_QOS_STRING";
  case MAGIC_ERROR_MALFORMED_TFT_STRING:
    return "MAGIC_ERROR_MALFORMED_TFT_STRING";
  case MAGIC_ERROR_MALFORMED_DATA_LINK_STRING:
    return "MAGIC_ERROR_MALFORMED_DATA_LINK_STRING";
  case MAGIC_ERROR_MALFORMED_CHANNEL_STATUS_STRING:
    return "MAGIC_ERROR_MALFORMED_CHANNEL_STATUS_STRING";
  case MAGIC_ERROR_ADD_SESSION_FAILED:
    return "MAGIC_ERROR_ADD_SESSION_FAILED";
  case MAGIC_ERROR_MODIFY_SESSION_FAILED:
    return "MAGIC_ERROR_MODIFY_SESSION_FAILED";
  case MAGIC_ERROR_OPEN_LINK_FAILED_DEPRECATED:
    return "MAGIC_ERROR_OPEN_LINK_FAILED_DEPRECATED";
  case MAGIC_ERROR_NO_ENTRY_IN_BANDWIDTHTABLE:
    return "MAGIC_ERROR_NO_ENTRY_IN_BANDWIDTHTABLE";
  case MAGIC_ERROR_NO_OPEN_LINKS:
    return "MAGIC_ERROR_NO_OPEN_LINKS";
  case MAGIC_ERROR_AMBIGUOUS_BANDWIDTHTABLE_PERCENTAGE:
    return "MAGIC_ERROR_AMBIGUOUS_BANDWIDTHTABLE_PERCENTAGE";
  case MAGIC_ERROR_NO_FREE_BANDWIDTH:
    return "MAGIC_ERROR_NO_FREE_BANDWIDTH";
  case MAGIC_ERROR_MISSING_PARAMETER:
    return "MAGIC_ERROR_MISSING_PARAMETER";
  case MAGIC_ERROR_CLIENT_REGISTRATION:
    return "MAGIC_ERROR_CLIENT_REGISTRATION";
  case MAGIC_ERROR_CLIENT_UNREGISTRATION:
    return "MAGIC_ERROR_CLIENT_UNREGISTRATION";
  case MAGIC_ERROR_ILLEGAL_FLIGHT_PHASE:
    return "MAGIC_ERROR_ILLEGAL_FLIGHT_PHASE";
  case MAGIC_ERROR_ILLEGAL_PARAMETER:
    return "MAGIC_ERROR_ILLEGAL_PARAMETER";
  case MAGIC_ERROR_STATUS_ACCESS_DENIED:
    return "MAGIC_ERROR_STATUS_ACCESS_DENIED";
  case MAGIC_ERROR_ACCOUNTING_ACCESS_DENIED:
    return "MAGIC_ERROR_ACCOUNTING_ACCESS_DENIED";
  case MAGIC_ERROR_ACCOUNTING_CONTROL_DENIED:
    return "MAGIC_ERROR_ACCOUNTING_CONTROL_DENIED";
  case MAGIC_ERROR_MAGIC_SHUTDOWN:
    return "MAGIC_ERROR_MAGIC_SHUTDOWN";
  case MAGIC_ERROR_ACCOUNTING_INVALID_CDRID:
    return "MAGIC_ERROR_ACCOUNTING_INVALID_CDRID";
  case MAGIC_ERROR_MALFORMED_CDR_STRING:
    return "MAGIC_ERROR_MALFORMED_CDR_STRING";
  case MAGIC_ERROR_SESSION_IS_BLOCKED_DEPRECATED:
    return "MAGIC_ERROR_SESSION_IS_BLOCKED_DEPRECATED";
  case MAGIC_ERROR_MALFORMED_NAPT_STRING:
    return "MAGIC_ERROR_MALFORMED_NAPT_STRING";
  case MAGIC_ERROR_MALFORMED_AIRPORTLIST_STRING:
    return "MAGIC_ERROR_MALFORMED_AIRPORTLIST_STRING";
  case MAGIC_ERROR_MALFORMED_FLIGHTPHASELIST_STRING:
    return "MAGIC_ERROR_MALFORMED_FLIGHTPHASELIST_STRING";
  case MAGIC_ERROR_MALFORMED_ALTITUDELIST_STRING:
    return "MAGIC_ERROR_MALFORMED_ALTITUDELIST_STRING";
  case MAGIC_ERROR_MALFORMED_DLMLIST_STRING:
    return "MAGIC_ERROR_MALFORMED_DLMLIST_STRING";
  case MAGIC_ERROR_MALFORMED_PRIO_CLASS_STRING:
    return "MAGIC_ERROR_MALFORMED_PRIO_CLASS_STRING";
  case MAGIC_ERROR_PROFILE_DOES_NOT_EXIST:
    return "MAGIC_ERROR_PROFILE_DOES_NOT_EXIST";
  case MAGIC_ERROR_TFT_INVALID:
    return "MAGIC_ERROR_TFT_INVALID";
  case MAGIC_ERROR_NAPT_INVALID:
    return "MAGIC_ERROR_NAPT_INVALID";

  /* MAGIC 信息码 (1038-1048) */
  case MAGIC_INFO_SET_LINK_QOS:
    return "MAGIC_INFO_SET_LINK_QOS";
  case MAGIC_INFO_REMOVE_LINK_QOS:
    return "MAGIC_INFO_REMOVE_LINK_QOS";
  case MAGIC_INFO_SET_DEFAULTROUTE:
    return "MAGIC_INFO_SET_DEFAULTROUTE";
  case MAGIC_INFO_REMOVE_DEFAULTROUTE:
    return "MAGIC_INFO_REMOVE_DEFAULTROUTE";
  case MAGIC_INFO_SET_POLICYROUTING:
    return "MAGIC_INFO_SET_POLICYROUTING";
  case MAGIC_INFO_REMOVE_POLICYROUTING:
    return "MAGIC_INFO_REMOVE_POLICYROUTING";
  case MAGIC_INFO_SET_NAPT:
    return "MAGIC_INFO_SET_NAPT";
  case MAGIC_INFO_REMOVE_NAPT:
    return "MAGIC_INFO_REMOVE_NAPT";
  case MAGIC_INFO_SET_SESSION_QOS:
    return "MAGIC_INFO_SET_SESSION_QOS";
  case MAGIC_INFO_REMOVE_SESSION_QOS:
    return "MAGIC_INFO_REMOVE_SESSION_QOS";
  case MAGIC_INFO_INTERNAL_ERROR:
    return "MAGIC_INFO_INTERNAL_ERROR";

  /* MAGIC 系统错误 (2000-2010) */
  case MAGIC_ERROR_AIS_INTERRUPTED:
    return "MAGIC_ERROR_AIS_INTERRUPTED";
  case MAGIC_ERROR_FLIGHT_PHASE_ERROR:
    return "MAGIC_ERROR_FLIGHT_PHASE_ERROR";
  case MAGIC_ERROR_AIRPORT_ERROR:
    return "MAGIC_ERROR_AIRPORT_ERROR";
  case MAGIC_ERROR_ALTITUDE_ERROR:
    return "MAGIC_ERROR_ALTITUDE_ERROR";
  case MAGIC_ERROR_NO_BANDWIDTH_ASSIGNMENT:
    return "MAGIC_ERROR_NO_BANDWIDTH_ASSIGNMENT";
  case MAGIC_ERROR_REQUEST_NOT_PROCESSED:
    return "MAGIC_ERROR_REQUEST_NOT_PROCESSED";
  case MAGIC_ERROR_OPEN_LINK_FAILED:
    return "MAGIC_ERROR_OPEN_LINK_FAILED";
  case MAGIC_ERROR_LINK_ERROR:
    return "MAGIC_ERROR_LINK_ERROR";
  case MAGIC_ERROR_CLOSE_LINK_FAILED:
    return "MAGIC_ERROR_CLOSE_LINK_FAILED";
  case MAGIC_ERROR_MAGIC_FAILURE:
    return "MAGIC_ERROR_MAGIC_FAILURE";
  case MAGIC_INFO_FORCED_REROUTING:
    return "MAGIC_INFO_FORCED_REROUTING";

  /* MAGIC 未知错误 (3000-3001) */
  case MAGIC_ERROR_UNKNOWN_ISSUE:
    return "MAGIC_ERROR_UNKNOWN_ISSUE";
  case MAGIC_ERROR_AVIONICSDATA_MISSING:
    return "MAGIC_ERROR_AVIONICSDATA_MISSING";

  default:
    return "UNKNOWN_MAGIC_STATUS";
  }
}
