#!/bin/bash
##############################################################################
# 手动测试网卡监控功能
##############################################################################

echo "=========================================="
echo "   网卡状态监控 - 手动测试指南"
echo "=========================================="
echo ""
echo "1. 启动服务器 (新终端):"
echo "   cd /home/zhuwuhui/freeDiameter/build"
echo "   sudo ./freeDiameterd/freeDiameterd -c ../conf/magic_server.conf 2>&1 | grep -E 'Link status|MSCR|timeout|Heartbeat'"
echo ""
echo "2. 启动 DLM_WIFI (新终端):"
echo "   cd /home/zhuwuhui/freeDiameter/DLM_WIFI"
echo "   sudo ./dlm_wifi_proto"
echo ""
echo "3. 禁用网卡测试 Link_Down 检测:"
echo "   sudo ip link set eth_wifi down"
echo "   (等待 5-10 秒观察 DLM 日志)"
echo "   预期: DLM 输出 '检测到网卡 eth_wifi 状态变为 DOWN'"
echo "   预期: DLM 发送 'Link_Down.indication'"
echo "   预期: 服务器输出 'Link status change: LINK_WIFI → DOWN'"
echo ""
echo "4. 重新启用网卡测试 Link_Up 检测:"
echo "   sudo ip link set eth_wifi up"
echo "   (等待 5-10 秒观察 DLM 日志)"
echo "   预期: DLM 输出 '检测到网卡 eth_wifi 状态变为 UP'"
echo "   预期: DLM 发送 'Link_Detected.indication'"
echo "   预期: DLM 自动发送 'Link_Up.indication'"
echo "   预期: 服务器输出 'Link status change: LINK_WIFI → UP'"
echo ""
echo "5. 测试心跳超时监控 (强制杀死 DLM):"
echo "   sudo killall -9 dlm_wifi_proto"
echo "   (等待 30 秒观察服务器日志)"
echo "   预期: 服务器输出 'DLM heartbeat timeout detected: LINK_WIFI'"
echo "   预期: 服务器输出 'Cleaned up timed-out DLM: LINK_WIFI'"
echo "   预期: 服务器输出 'Link status change: LINK_WIFI → DOWN'"
echo ""
echo "=========================================="
echo "关键改进说明:"
echo "=========================================="
echo ""
echo "✓ DLM 现在会监控网卡物理状态 (/sys/class/net/*/operstate)"
echo "✓ 网卡 DOWN 时自动发送 Link_Down.indication"
echo "✓ 网卡 UP 时自动发送 Link_Detected + Link_Up"
echo "✓ 服务器有心跳超时监控 (30秒超时, 10秒检查间隔)"
echo "✓ 心跳超时时自动触发 LINK_EVENT_DOWN"
echo "✓ 两种机制互补: 主动监控 + 被动超时检测"
echo ""
echo "=========================================="
echo "网卡状态文件说明:"
echo "=========================================="
echo ""
echo "查看网卡状态:"
echo "  cat /sys/class/net/eth_wifi/operstate"
echo ""
echo "可能的状态值:"
echo "  - up:      网卡已启用且有链路 (正常工作)"
echo "  - down:    网卡已禁用"
echo "  - unknown: 网卡存在但状态未知"
echo ""
echo "DLM 仅在 operstate='up' 时发送心跳"
echo ""
